### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by LI-YONG-QI** [LI-YONG-QI/airdrop-bot#1]
p0
- [x] uniswap router parameters
- [x] improve publish package CI/CD
- [x] refactor contract interaction class
- [x] cronjob structure
- [ ] support another protocol (Hypelane / Movement / Eclipse / Avail)

p1
- [x] cli
- [x] linter / prettier
- [ ] add new --rpc options
- [x] publish version control
- [x] update private key and amount to command argument

p2
- [ ] large wallets
